version: '3.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.example.com
      - VIRTUAL_PORT=9000
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  app:
    image: fireflyiii/core:latest
    container_name: fireflyiii-app
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ff3.env
    environment:
      - VIRTUAL_HOST=firefly3.example.com
      - VIRTUAL_PORT=8080
      - APP_URL=https://firefly3.example.com
      - TRUSTED_PROXIES=**
      - TZ=America/Los_Angeles
    depends_on:
      - db

  db:
    image: mariadb
    container_name: ff3-db
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=somerandompassword
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql

  fidi:
    container_name: ff3-fidi
    image: fireflyiii/data-importer:latest
    env_file: fidi.env
    environment:
      - VIRTUAL_HOST=fidi.example.com
      - VIRTUAL_PORT=8080
      - APP_URL=https://fidi.example.com
      - TRUSTED_PROXIES=**
    depends_on:
      - app
volumes:
  firefly_iii_upload:
  firefly_iii_db:
